### ISSUE TITLE
♥ the new name!  

### ISSUE THREAD

**Issue by PySimpleGUI** [definite-d/PSG-LookyFeely#11]
Very nice you're keeping the project moving forward, always improving, building, changing, .... it's great stuff to see!  It's inspirational to watch other inspired people.

I like the logo!  

Question for you on this screenshot, of course:

![image](https://user-images.githubusercontent.com/46163555/121011161-4d272480-c764-11eb-9123-457657c58f83.png)

What technique did you use to get the background image / colors?  Always on the hunt for new methods for doing things in GUIs.

Keep moving!  It's awesome to see!

**Comment by definite-d** [comment]
Thanks!

Glad to know the project is appreciated!

Well, that screenshot is an edited image of three different screenshots actually. It's there to simply showcase that Themera is fully capable of using all of the default themes as well as the custom ones.

It's not an actual window. Sorry!
