### ISSUE TITLE
[Suggestion] Custom layout preview

### ISSUE THREAD

**Issue by WarnerMeinshegran** [definite-d/PSG-LookyFeely#12]
Hello @definite-d !
I have a suggestion for themera.
I usually prefer to use my program layout as a preview for the theme being built by themera, so would you kindly allow for custom layout used for preview.

**Comment by definite-d** [comment]
Hey, @blabla-labALT 

Sorry for not responding sooner, but I've been aware of your request and had begun working on it a while back. I decided to respond when I completed your request instead.

This suggestion of yours is now officially a feature; you can now select the type of Full Preview to use from Settings. It's available in the latest [v2.1.0 release](https://github.com/definite-d/Themera/releases/tag/v2.1.0). Please check it out and let me know what you think.

I believe this is taken care of, so I'm closing this issue, but will reopen it if necessary.

Cheers!

**Comment by blabla-labALT** [comment]
Thanks!
