### ISSUE TITLE
❤ your work!

### ISSUE THREAD

**Issue by PySimpleGUI** [definite-d/PSG-LookyFeely#13]
![image](https://github.com/definite-d/Themera/assets/46163555/22f156f3-1f57-4374-a746-e698650d11ee)

Love the work you've done on this project since 2019.  It takes a tremendous amount of dedication and energy to build, extend, maintain, and support the kind of utility you've built.  It's inspiring to see other developers like yourself that have passion driving their work.  ![image](https://github.com/definite-d/Themera/assets/46163555/87dc46f6-2f12-45e3-97ac-727320205fde)  **Very** nicely done!

**Comment by definite-d** [comment]
Thanks for the kind words @PySimpleGUI 🙌🏾, and for keeping the  PySimpleGUI project active yourself.

It's been a great journey of learning, and I've loved every step of the way.

**Comment by PySimpleGUI** [comment]
Hiya... can you drop me an email.  I'm sorry I've managed to lose y address again.
![image](https://github.com/definite-d/Themera/assets/46163555/2f916768-4fe6-4d5b-9da3-ae435dbe3e75)
