### ISSUE TITLE
Screenshots in your readme!

### ISSUE THREAD

**Issue by PySimpleGUI** [definite-d/PSG-LookyFeely#9]
I just noticed that you don't have screenshots in your readme.  I'm not sure hope I managed to miss this all this time.  I'm sure adding some shots to your readme will get you a bit more attention.  You've already got a folder full of them.

![](https://raw.githubusercontent.com/definite-d/PSG-LookyFeely/master/screenshots/v2/1.PNG)
![](https://raw.githubusercontent.com/definite-d/PSG-LookyFeely/master/screenshots/v2/2.PNG)
![](https://raw.githubusercontent.com/definite-d/PSG-LookyFeely/master/screenshots/v2/3.PNG)
![](https://raw.githubusercontent.com/definite-d/PSG-LookyFeely/master/screenshots/v2/4.PNG)
![](https://raw.githubusercontent.com/definite-d/PSG-LookyFeely/master/screenshots/v2/5.PNG)
![](https://raw.githubusercontent.com/definite-d/PSG-LookyFeely/master/screenshots/v2/6.PNG)
![](https://raw.githubusercontent.com/definite-d/PSG-LookyFeely/master/screenshots/v2/7.PNG)
![](https://raw.githubusercontent.com/definite-d/PSG-LookyFeely/master/screenshots/v2/8.PNG)
![](https://raw.githubusercontent.com/definite-d/PSG-LookyFeely/master/screenshots/v2/9.PNG)
![](https://raw.githubusercontent.com/definite-d/PSG-LookyFeely/master/screenshots/v2/10.PNG)
![](https://raw.githubusercontent.com/definite-d/PSG-LookyFeely/master/screenshots/v2/11.PNG)

**Comment by definite-d** [comment]
Whoa, could you believe that I didn't notice that?

I'll add some shots in. Thanks!

**Comment by definite-d** [comment]
I figured I'd put the most recent screenshots in this issue. So...

![04](https://user-images.githubusercontent.com/38317208/96386301-cb14cc00-1191-11eb-8391-13c2453b835a.PNG)
![03](https://user-images.githubusercontent.com/38317208/96386303-cd772600-1191-11eb-9368-6634efda1c5a.PNG)
![01](https://user-images.githubusercontent.com/38317208/96386304-ce0fbc80-1191-11eb-8369-f81ee08ac020.PNG)
![05](https://user-images.githubusercontent.com/38317208/96386305-cea85300-1191-11eb-9f79-4ab81421fcdc.PNG)
![02](https://user-images.githubusercontent.com/38317208/96386306-cf40e980-1191-11eb-891f-86ffa291b256.PNG)
